### ISSUE TITLE
Should `checkupdate` be a thing?

### ISSUE THREAD

**Issue by baseplate-admin** [hitblast/avro.py#53]
https://github.com/hitblast/avro.py/blob/4d59e86b96874ed5b76011db62ae94d268032cac/avro/cli.py#L123-L139

I have never come across such a pattern in a lib. If user wants to see update, they should use `UV`, `Poetry`, `PDM`. Bundling `requests` into such an application seems weird pattern

**Comment by baseplate-admin** [comment]
> but also a to-be hybrid package at this point.

Then it's time to decouple things i presume. Because the way things are currently structured, the package is getting bloated. Like if i want to use avro.py in a server context (@TanimSk probably used this) or a gui context , i have almost zero need for the CLI and other added things.

> Homebrew in this might be the first one. 

If this is the goal, still i dont get why you should check github for new version. You can use github actions to do a new release to homebrew package manager and then when system updates, it will pick the new one. 

Here are my advises:
1. One package should do one thing and one thing well. ( i am talking about making something like `avro.py` that does the basic things and `avro.py-cli` for other type of things )
2. Make a monorepo.

**Comment by hitblast** [comment]
@baseplate-admin Noted. And as of the bloat thing, I'll probably remove the `checkupdate` command and try to add some other commands based on the internal components instead of using third-party dependencies. Since the CLI can only be run when installed with `pip install avro.py[cli]`, I don't think this will be a hassle after this change. Thanks for your other suggestions too!
